import { createServerFn } from "@tanstack/react-start";
import { callAiGatewayWithRotation, getActiveAiKey } from "@/lib/ai-keys.functions";

async function getAdmin() {
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  return supabaseAdmin as any;
}

// AI quiz generator — NEET-grade chapter-wise DPP with varied question types.
// • 20 questions per quiz, one chapter per quiz
// • Live window: today 10:00 IST → 22:00 IST

type QType =
  | "numerical"
  | "assertion-reason"
  | "statement-based"
  | "match-the-following"
  | "ranking"
  | "graphical"
  | "diagram-based"
  | "case-based"
  | "fill-in-the-blanks"
  | "incorrect-statement"
  | "reaction-sequence"
  | "concept-mcq";

type GenQ = {
  type: QType;
  text: string;
  options: [string, string, string, string];
  correct_index: 0 | 1 | 2 | 3;
  explanation: string;
  difficulty: "Easy" | "Medium" | "Hard";
  source?: string;
};

// Turn an AI-supplied citation into a clean exam-style source label.
// We NEVER expose "AI" to students — only real exam / book references.
function examSource(raw?: string | null): string {
  const s = (raw ?? "").trim();
  if (!s || /\bai\b/i.test(s) || /^ai[-\s]/i.test(s)) {
    // Sensible default rotation of legit sources.
    const fallbacks = ["NCERT", "NEET PYQ", "AIPMT", "JEE"];
    return fallbacks[Math.floor(Math.random() * fallbacks.length)];
  }
  return s.slice(0, 60);
}

const NEET_MASTER_SYSTEM = `You are an elite NEET-UG / IIT-JEE question setter. Generate high-yield, exam-standard, unique MCQs from the rationalized NCERT syllabus (Classes 11 & 12).

## OUTPUT
Return ONLY a JSON tool call. Every field populated.

## LATEX RULES
- Wrap every variable, unit, value, formula, constant, ratio in LaTeX.
- Inline: $v = u + at$. Display: $$E = mc^2$$.
- Single backslash inside JSON strings. Never break \`$\` delimiters.

## QUESTION-TYPE MIX (every batch must vary across these)
1. **numerical** — multi-step computations.
2. **assertion-reason** — A + R with 4 standard options below.
3. **statement-based** — "Which is INCORRECT?" / "How many are correct?"
4. **match-the-following** — MUST use a LaTeX array table (see exact format below). DO NOT use markdown pipe tables.
5. **ranking** — order by strength / priority / stability.
6. **graphical** — interpret slope, area, inflection points.
7. **diagram-based** — SKIP in this batch. Diagram questions are generated by a separate PNG pipeline. Never emit \`\`\`tikz\`\`\`, \`\`\`mermaid\`\`\`, or inline <svg> blocks; never describe imaginary diagrams.
8. **case-based** — short passage + MCQ.
9. **fill-in-the-blanks** — direct NCERT lines.
10. **incorrect-statement** — pick the wrong statement.
11. **reaction-sequence** — $A \\xrightarrow{R_1} B \\xrightarrow{R_2} C$.
12. **concept-mcq** — single concept.

## MATCH-THE-FOLLOWING — EXACT FORMAT (mandatory)
Text MUST follow this template (LaTeX array, NOT markdown table):

\`Match the following ...:\\n\\n$$\\n\\\\begin{array}{|c|c|}\\n\\\\hline\\n\\\\textbf{Column I} & \\\\textbf{Column II} \\\\\\\\\\n\\\\hline\\nA.\\\\ \\\\text{...} & i.\\\\ \\\\text{...} \\\\\\\\\\n\\\\hline\\nB.\\\\ \\\\text{...} & ii.\\\\ \\\\text{...} \\\\\\\\\\n\\\\hline\\nC.\\\\ \\\\text{...} & iii.\\\\ \\\\text{...} \\\\\\\\\\n\\\\hline\\nD.\\\\ \\\\text{...} & iv.\\\\ \\\\text{...} \\\\\\\\\\n\\\\hline\\n\\\\end{array}\\n$$\\n\\nSelect the correct matching sequence:\`

Options MUST look like: "A-iii, B-i, C-ii, D-iv".

## ASSERTION-REASON OPTIONS (exact wording)
A) Both A and R are true and R is the correct explanation of A.
B) Both A and R are true but R is NOT the correct explanation of A.
C) A is true but R is false.
D) A is false but R is true.
Text: \`**Assertion (A):** ...\\n\\n**Reason (R):** ...\`

## QUALITY
- No two questions test the same trap. All distractors plausible. Exactly one correct option. Mix Easy/Medium/Hard. Spread correct answer across A/B/C/D.

## EXPLANATION — SHORT, CLEAR, UNDERSTANDING FIRST
Write a CONCISE explanation (4–8 lines max) that a student instantly understands. NO long derivations, NO 4-section template, NO heavy headers.
Structure:
- One line stating the key concept / NCERT fact.
- 1–3 lines showing the crucial calculation or reasoning (with LaTeX).
- One line ruling out the closest distractor.
- End with: \`**Answer: Option X.**\`
Prefer clarity over completeness. Understanding > length.`;

async function generateNeetMcqs(
  subjectName: string,
  chapterName: string,
  classNum: number,
  n: number,
): Promise<GenQ[]> {
  const user = `Subject: ${subjectName}
Chapter: "${chapterName}" (Class ${classNum})
Produce ${n} unique NEET-grade MCQs strictly from this chapter using a VARIED mix. Aim for: ~4 numerical, ~3 assertion-reason, ~3 statement-based, ~2 match-the-following (use the EXACT LaTeX array format from the system prompt — no markdown pipe tables), ~2 ranking, ~2 graphical, rest case-based / concept-mcq / incorrect-statement / reaction-sequence. DO NOT emit any diagram-based questions or any \`\`\`tikz\`\`\`/\`\`\`mermaid\`\`\`/<svg> blocks. Keep explanations short and clear (4–8 lines). For each question also give a realistic exam "source" citation such as "NCERT Class ${classNum} Pg 142", "NEET 2019", "AIPMT 2014" or "JEE Main 2022". NEVER write "AI" anywhere in the source.`;

  const res = await callAiGatewayWithRotation("/v1/chat/completions", {
    model: "google/gemini-2.5-flash",
    messages: [
      { role: "system", content: NEET_MASTER_SYSTEM },
      { role: "user", content: user },
    ],
    tools: [{
      type: "function",
      function: {
        name: "emit_questions",
        parameters: {
          type: "object",
          properties: {
            questions: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  type: { type: "string", enum: [
                    "numerical","assertion-reason","statement-based","match-the-following",
                    "ranking","graphical","diagram-based","case-based","fill-in-the-blanks",
                    "incorrect-statement","reaction-sequence","concept-mcq",
                  ] },
                  text: { type: "string" },
                  options: { type: "array", items: { type: "string" }, minItems: 4, maxItems: 4 },
                  correct_index: { type: "integer", minimum: 0, maximum: 3 },
                  explanation: { type: "string" },
                  difficulty: { type: "string", enum: ["Easy","Medium","Hard"] },
                  source: { type: "string" },
                },
                required: ["type","text","options","correct_index","explanation","difficulty"],
                additionalProperties: false,
              },
            },
          },
          required: ["questions"],
          additionalProperties: false,
        },
      },
    }],
    tool_choice: { type: "function", function: { name: "emit_questions" } },
  });

  const data = await res.json();
  const args = data?.choices?.[0]?.message?.tool_calls?.[0]?.function?.arguments;
  if (!args) throw new Error("AI did not return tool call");
  const parsed = JSON.parse(args) as { questions: GenQ[] };
  return (parsed.questions ?? []).filter(
    (q) => q.text && q.options?.length === 4 && q.correct_index >= 0 && q.correct_index <= 3,
  );
}

function liveWindowToday() {
  const now = new Date();
  const istOffsetMs = 5.5 * 60 * 60 * 1000;
  const istNow = new Date(now.getTime() + istOffsetMs);
  const y = istNow.getUTCFullYear();
  const m = istNow.getUTCMonth();
  const d = istNow.getUTCDate();
  const startsAt = new Date(Date.UTC(y, m, d, 10, 0, 0) - istOffsetMs).toISOString();
  const endsAt = new Date(Date.UTC(y, m, d, 22, 0, 0) - istOffsetMs).toISOString();
  return { startsAt, endsAt };
}

async function pickChapters(limit: number) {
  const supabaseAdmin = await getAdmin();
  const { data: chapters } = await supabaseAdmin
    .from("chapters")
    .select("id,name,class,subject_id,subjects:subject_id(name)")
    .order("order_index", { ascending: true });
  if (!chapters || chapters.length === 0) return [];

  // Count existing daily quizzes per chapter (covers weightage-wise rotation)
  const { data: dailyTests } = await supabaseAdmin
    .from("tests")
    .select("question_ids")
    .eq("type", "daily");
  const allQids = Array.from(new Set((dailyTests ?? []).flatMap((t) => (t.question_ids ?? []) as string[])));
  const chapterCount = new Map<string, number>();
  if (allQids.length > 0) {
    // Batch in chunks to avoid URL length issues
    const chunkSize = 200;
    for (let i = 0; i < allQids.length; i += chunkSize) {
      const chunk = allQids.slice(i, i + chunkSize);
      const { data: qs } = await supabaseAdmin
        .from("questions")
        .select("chapter_id")
        .in("id", chunk);
      (qs ?? []).forEach((q) => {
        if (q.chapter_id) chapterCount.set(q.chapter_id, (chapterCount.get(q.chapter_id) ?? 0) + 1);
      });
    }
  }

  const seed = new Date().toISOString().slice(0, 10);
  const seedKey = (id: string) => (id + seed).split("").reduce((s, c) => s + c.charCodeAt(0), 0);

  // Sort: fewest existing questions first (covers untouched chapters),
  // then deterministic shuffle by date seed for variety.
  const sorted = [...chapters].sort((a, b) => {
    const ca = chapterCount.get(a.id) ?? 0;
    const cb = chapterCount.get(b.id) ?? 0;
    if (ca !== cb) return ca - cb;
    return seedKey(a.id) - seedKey(b.id);
  });

  // Ensure subject spread within the picked batch (round-robin across subjects)
  const bySubject = new Map<string, typeof sorted>();
  for (const ch of sorted) {
    const k = ch.subject_id;
    if (!bySubject.has(k)) bySubject.set(k, []);
    bySubject.get(k)!.push(ch);
  }
  const subjectKeys = [...bySubject.keys()].sort((a, b) => seedKey(a) - seedKey(b));
  const picked: typeof sorted = [];
  const usedIds = new Set<string>();
  let i = 0;
  while (picked.length < limit && subjectKeys.length > 0) {
    const key = subjectKeys[i % subjectKeys.length];
    const list = bySubject.get(key)!;
    const next = list.shift();
    if (next && !usedIds.has(next.id)) {
      picked.push(next);
      usedIds.add(next.id);
    }
    if (list.length === 0) subjectKeys.splice(i % subjectKeys.length, 1);
    else i++;
    if (subjectKeys.length === 0) break;
  }
  return picked as Array<{
    id: string; name: string; class: number | null;
    subject_id: string; subjects: { name: string } | null;
  }>;
}

async function nextQuizSerial(chapterName: string): Promise<number> {
  const supabaseAdmin = await getAdmin();
  const { count } = await supabaseAdmin
    .from("tests")
    .select("id", { count: "exact", head: true })
    .ilike("title", `${chapterName} • Quiz %`);
  return (count ?? 0) + 1;
}

async function buildDiagramQuestionIds(chapter: {
  id: string; name: string; class: number | null;
  subject_id: string; subjects: { name: string } | null;
}, wanted: number): Promise<{ ids: string[]; errors: string[] }> {
  const supabaseAdmin = await getAdmin();
  const subjName = chapter.subjects?.name ?? "Science";
  const ids: string[] = [];
  const errors: string[] = [];
  try {
    const drafts = await generateDiagramOnlyMcqs(subjName, chapter.name, chapter.class ?? 12, wanted);
    for (const d of drafts.slice(0, wanted)) {
      try {
        const { data: qRow, error: qErr } = await supabaseAdmin
          .from("questions")
          .insert({
            subject_id: chapter.subject_id,
            chapter_id: chapter.id,
            text: d.text,
            options: d.options,
            correct_index: d.correct_index,
            explanation: d.explanation ?? null,
            difficulty: (d.difficulty ?? "Medium").toLowerCase(),
            source: "NCERT",
            marks_correct: 4,
            marks_wrong: -1,
          })
          .select("id")
          .single();
        if (qErr || !qRow) throw qErr ?? new Error("question insert failed");
        const qid = qRow.id as string;
        const b64 = await renderDiagramPng(d.image_prompt);
        const { data: diagRow, error: dErr } = await supabaseAdmin
          .from("question_diagrams")
          .insert({ question_id: qid, mime: "image/png", data: `\\x${Buffer.from(b64, "base64").toString("hex")}`, prompt: d.image_prompt })
          .select("id")
          .single();
        if (dErr || !diagRow) throw dErr ?? new Error("diagram insert failed");
        const url = `/api/public/diagram/${diagRow.id}.png`;
        const newText = `![diagram](${url})\n\n${d.text}`;
        const { error: uErr } = await supabaseAdmin
          .from("questions").update({ text: newText }).eq("id", qid);
        if (uErr) throw uErr;
        ids.push(qid);
      } catch (e) {
        errors.push(e instanceof Error ? e.message : String(e));
      }
    }
  } catch (e) {
    errors.push(e instanceof Error ? e.message : String(e));
  }
  return { ids, errors };
}

async function createOneAiQuiz(chapter: {
  id: string; name: string; class: number | null;
  subject_id: string; subjects: { name: string } | null;
}) {
  const supabaseAdmin = await getAdmin();
  const subjName = chapter.subjects?.name ?? "Science";
  // 18 text-MCQs + 2 diagram-MCQs = 20 total per quiz.
  const qs = await generateNeetMcqs(subjName, chapter.name, chapter.class ?? 12, 18);
  if (qs.length < 5) throw new Error(`AI returned only ${qs.length} questions for ${chapter.name}`);

  const { data: insertedQ, error: qErr } = await supabaseAdmin
    .from("questions")
    .insert(
      qs.map((q) => ({
        subject_id: chapter.subject_id,
        chapter_id: chapter.id,
        text: q.text,
        options: q.options,
        correct_index: q.correct_index,
        explanation: q.explanation ?? null,
        difficulty: (q.difficulty ?? "Medium").toLowerCase(),
        source: examSource(q.source),
        marks_correct: 4,
        marks_wrong: -1,
      })),
    )
    .select("id");
  if (qErr) throw qErr;
  const textIds = (insertedQ ?? []).map((r: { id: string }) => r.id);

  // Best-effort: add 2 diagram/graph questions. Quiz still ships if these fail.
  const diag = await buildDiagramQuestionIds(chapter, 2);
  const ids = [...textIds, ...diag.ids];

  const { startsAt, endsAt } = liveWindowToday();
  const serial = await nextQuizSerial(chapter.name);

  const { error: tErr } = await supabaseAdmin.from("tests").insert({
    title: `${chapter.name} • Quiz ${serial}`,
    description: `NEET DPP · ${subjName} · ${chapter.name}. Live 10 AM – 10 PM IST.`,
    type: "daily",
    difficulty: "medium",
    duration_min: 25,
    total_questions: ids.length,
    is_paid: false,
    starts_at: startsAt,
    ends_at: endsAt,
    question_ids: ids,
    marks_correct: 4,
    marks_wrong: -1,
    source: "NCERT & PYQ",
  });
  if (tErr) throw tErr;
  return { chapter: chapter.name, count: ids.length, serial };
}

export const generateAiDailyQuizzes = createServerFn({ method: "POST" })
  .inputValidator((d: { count?: number }) => ({
    count: Math.min(Math.max(d?.count ?? 1, 1), 20),
  }))
  .handler(async ({ data }) => {
    const chapters = await pickChapters(data.count);
    if (chapters.length === 0) {
      return { created: 0, errors: ["No chapters in database. Add chapters first."], results: [] };
    }
    let created = 0;
    const errors: string[] = [];
    const results: Array<{ chapter: string; count: number; serial: number }> = [];
    for (const ch of chapters) {
      try {
        const r = await createOneAiQuiz(ch);
        results.push(r);
        created++;
      } catch (e) {
        errors.push(`${ch.name}: ${e instanceof Error ? e.message : String(e)}`);
      }
    }
    return { created, errors, results };
  });

// ------------------------------------------------------------
// Diagram-only DPP — AI generates a real PNG diagram per question.
// Pipeline: AI writes question + image_prompt → image gateway renders PNG →
// PNG bytes stored in `question_diagrams` → question text embeds
// `![diagram](/api/public/diagram/<id>)`.
// ------------------------------------------------------------

const DIAGRAM_ONLY_SYSTEM = `You are a NEET-UG question setter creating DIAGRAM/GRAPH based MCQs.
For each question, write ONLY the prose stem (no ASCII art, no \`\`\`tikz, no \`\`\`mermaid, no <svg>, no markdown image).
A separate AI image generator will draw a clean NCERT-replica diagram from your "image_prompt".

VARIETY — rotate across these diagram-question types:
- Identify the labelled part (P)/(Q)/(R)/(S) in a biological or physical diagram.
- Choose the CORRECT statement about a labelled structure / path / pathway.
- Choose the INCORRECT statement about the labelled diagram.
- Graph/curve analysis: slope, region, peak, turning point, intercept, or what a labelled segment represents.
- Match labelled parts (P,Q,R,S) with their function/name (options like "P-iii, Q-i, R-iv, S-ii").
- Sequence/flow ordering (steps of a cycle, blood-flow direction, signal path).
- Numerical reading from a graph (slope, area, ratio).

Rules:
- "image_prompt": precise NCERT-style textbook diagram description. Mention labelled parts as (P), (Q), (R), (S). For graphs, describe axes (with units), curve shape, and labelled segments/points. Style: clean black-on-white NCERT line drawing, labelled clearly, no shading, no watermark, no extra text.
- "text": the question stem referring to labelled parts. Do NOT redescribe the diagram in words.
- 4 options, exactly one correct, mix Easy/Medium/Hard, spread correct across A/B/C/D.
- LaTeX inline $...$, block $$...$$. Single backslashes inside JSON.
- Explanation 4–6 short lines, end with **Answer: Option X.**`;

type DiagQ = {
  text: string;
  image_prompt: string;
  options: [string, string, string, string];
  correct_index: 0 | 1 | 2 | 3;
  explanation: string;
  difficulty: "Easy" | "Medium" | "Hard";
};

async function generateDiagramOnlyMcqs(
  subjectName: string,
  chapterName: string,
  classNum: number,
  n: number,
): Promise<DiagQ[]> {
  const user = `Subject: ${subjectName}\nChapter: "${chapterName}" (Class ${classNum})\nProduce ${n} diagram-based MCQs. For each, give a concise textbook-style "image_prompt" so a separate image AI can render the diagram. The stem must reference labelled parts (P)/(Q)/(R)/(S) from the diagram.`;
  const res = await callAiGatewayWithRotation("/v1/chat/completions", {
    model: "google/gemini-2.5-flash",
    messages: [
      { role: "system", content: DIAGRAM_ONLY_SYSTEM },
      { role: "user", content: user },
    ],
    tools: [{
      type: "function",
      function: {
        name: "emit_questions",
        parameters: {
          type: "object",
          properties: {
            questions: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  text: { type: "string" },
                  image_prompt: { type: "string" },
                  options: { type: "array", items: { type: "string" }, minItems: 4, maxItems: 4 },
                  correct_index: { type: "integer", minimum: 0, maximum: 3 },
                  explanation: { type: "string" },
                  difficulty: { type: "string", enum: ["Easy","Medium","Hard"] },
                },
                required: ["text","image_prompt","options","correct_index","explanation","difficulty"],
                additionalProperties: false,
              },
            },
          },
          required: ["questions"],
          additionalProperties: false,
        },
      },
    }],
    tool_choice: { type: "function", function: { name: "emit_questions" } },
  });
  const data = await res.json();
  const args = data?.choices?.[0]?.message?.tool_calls?.[0]?.function?.arguments;
  if (!args) throw new Error("AI did not return tool call");
  const parsed = JSON.parse(args) as { questions: DiagQ[] };
  return (parsed.questions ?? []).filter(
    (q) => q.text && q.image_prompt && q.options?.length === 4,
  );
}

async function renderDiagramPng(prompt: string): Promise<string> {
  const apiKey = await getActiveAiKey();
  const full = `Clean black-on-white textbook line diagram, crisp lines, labelled parts (P)(Q)(R)(S) where relevant, no shading, no watermark, no extra text. ${prompt}`;
  // Primary: OpenAI gpt-image-2 (prompt shape)
  let res = await fetch("https://ai.gateway.lovable.dev/v1/images/generations", {
    method: "POST",
    headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
    body: JSON.stringify({ model: "openai/gpt-image-2", prompt: full, quality: "low", size: "1024x1024", n: 1 }),
  });
  if (!res.ok) {
    // Fallback: Gemini image (messages + modalities shape)
    res = await fetch("https://ai.gateway.lovable.dev/v1/images/generations", {
      method: "POST",
      headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-image",
        messages: [{ role: "user", content: full }],
        modalities: ["image", "text"],
      }),
    });
    if (!res.ok) throw new Error(`Image gateway error ${res.status}: ${await res.text()}`);
  }
  const j = await res.json();
  const b64 = j?.data?.[0]?.b64_json;
  if (!b64) throw new Error("Image gateway returned no b64_json");
  return b64;
}

export const generateAiDiagramDpp = createServerFn({ method: "POST" })
  .inputValidator((d: { count?: number }) => ({ count: Math.min(Math.max(d?.count ?? 10, 3), 15) }))
  .handler(async ({ data }) => {
    const supabaseAdmin = await getAdmin();
    const chapters = await pickChapters(1);
    if (chapters.length === 0) throw new Error("No chapters in DB");
    const ch = chapters[0];
    const subjName = ch.subjects?.name ?? "Science";
    const drafts = await generateDiagramOnlyMcqs(subjName, ch.name, ch.class ?? 12, data.count);
    if (drafts.length < 3) throw new Error(`AI returned only ${drafts.length} drafts`);

    const insertedIds: string[] = [];
    const errors: string[] = [];
    for (const d of drafts) {
      try {
        // 1) insert question shell to obtain id (used as fk target)
        const { data: qRow, error: qErr } = await supabaseAdmin
          .from("questions")
          .insert({
            subject_id: ch.subject_id,
            chapter_id: ch.id,
            text: d.text, // updated below with image url
            options: d.options,
            correct_index: d.correct_index,
            explanation: d.explanation ?? null,
            difficulty: (d.difficulty ?? "Medium").toLowerCase(),
            source: "NCERT",
            marks_correct: 4,
            marks_wrong: -1,
          })
          .select("id")
          .single();
        if (qErr || !qRow) throw qErr ?? new Error("question insert failed");
        const qid = qRow.id as string;

        // 2) render PNG and store bytes
        const b64 = await renderDiagramPng(d.image_prompt);
        const { data: diagRow, error: dErr } = await supabaseAdmin
          .from("question_diagrams")
          .insert({ question_id: qid, mime: "image/png", data: `\\x${Buffer.from(b64, "base64").toString("hex")}`, prompt: d.image_prompt })
          .select("id")
          .single();
        if (dErr || !diagRow) throw dErr ?? new Error("diagram insert failed");

        // 3) update question text to embed the rendered image
        const url = `/api/public/diagram/${diagRow.id}.png`;
        const newText = `![diagram](${url})\n\n${d.text}`;
        const { error: uErr } = await supabaseAdmin
          .from("questions").update({ text: newText }).eq("id", qid);
        if (uErr) throw uErr;
        insertedIds.push(qid);
      } catch (e) {
        errors.push(e instanceof Error ? e.message : String(e));
      }
    }
    if (insertedIds.length === 0) throw new Error(`No questions saved. ${errors.join(" | ")}`);

    const { startsAt, endsAt } = liveWindowToday();
    const serial = await nextQuizSerial(ch.name);
    const { data: t, error: tErr } = await supabaseAdmin.from("tests").insert({
      title: `${ch.name} • Diagram DPP ${serial}`,
      description: `Diagram-only DPP · ${subjName} · ${ch.name}.`,
      type: "daily",
      difficulty: "medium",
      duration_min: 20,
      total_questions: insertedIds.length,
      is_paid: false,
      starts_at: startsAt,
      ends_at: endsAt,
      question_ids: insertedIds,
      marks_correct: 4,
      marks_wrong: -1,
      source: "NCERT & PYQ",
    }).select("id").single();
    if (tErr) throw tErr;
    return { test_id: t?.id, chapter: ch.name, count: insertedIds.length, errors };
  });


