/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminCollaboratorsRouteImport } from './routes/admin-collaborators'
import { Route as AiPathRouteImport } from './routes/ai-path'
import { Route as ConsultRouteImport } from './routes/consult'
import { Route as ShortNotesRouteImport } from './routes/short-notes'
import { Route as MegaQuizRouteImport } from './routes/mega-quiz'
import { Route as Target700RouteImport } from './routes/target-700'
import { Route as Target700TestTestIdRouteImport } from './routes/target-700-test.$testId'
import { Route as NotesSubjectSlugRouteImport } from './routes/notes.$subject.$slug'
import { Route as ConsultPlanRouteImport } from './routes/consult-plan'
import { Route as ConsultReportRouteImport } from './routes/consult-report'
import { Route as ConsultScoreRouteImport } from './routes/consult-score'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BattlegroundsRouteImport } from './routes/battlegrounds'
import { Route as BonusRouteImport } from './routes/bonus'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as CollaboratorsRouteImport } from './routes/collaborators'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContestsRouteImport } from './routes/contests'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DedicatedProgramRouteImport } from './routes/dedicated-program'
import { Route as DppRouteImport } from './routes/dpp'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as HighlightedNcertRouteImport } from './routes/highlighted-ncert'
import { Route as InfiniteRunRouteImport } from './routes/infinite-run'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MentorshipRouteImport } from './routes/mentorship'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as MocksRouteImport } from './routes/mocks'
import { Route as NcertHighlightsRouteImport } from './routes/ncert-highlights'
import { Route as NeetlabRouteImport } from './routes/neetlab'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PyqsRouteImport } from './routes/pyqs'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as ScorePredictorRouteImport } from './routes/score-predictor'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as TodoRouteImport } from './routes/todo'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminInboxRouteImport } from './routes/admin.inbox'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AnalysisAttemptIdRouteImport } from './routes/analysis.$attemptId'
import { Route as BattlegroundsHistoryRouteImport } from './routes/battlegrounds.history'
import { Route as BattlegroundsViewAllRouteImport } from './routes/battlegrounds.view-all'
import { Route as ContestContestIdRouteImport } from './routes/contest.$contestId'
import { Route as PreviewHumanReproductionRouteImport } from './routes/preview.human-reproduction'
import { Route as QuizIndexRouteImport } from './routes/quiz.index'
import { Route as QuizTestIdRouteImport } from './routes/quiz.$testId'
import { Route as SubjectsSubjectRouteImport } from './routes/subjects.$subject'
import { Route as ApiPublicAppVersionRouteImport } from './routes/api/public/app-version'
import { Route as BattleMatchIdPlayRouteImport } from './routes/battle.$matchId.play'
import { Route as BattleMatchIdResultRouteImport } from './routes/battle.$matchId.result'
import { Route as ContestContestIdJoinRouteImport } from './routes/contest.$contestId.join'
import { Route as ContestContestIdResultsRouteImport } from './routes/contest.$contestId.results'
import { Route as ApiPublicCronDailyContestRouteImport } from './routes/api/public/cron.daily-contest'
import { Route as ApiPublicCronPushRunRouteImport } from './routes/api/public/cron.push-run'
import { Route as ApiPublicPushLatestRouteImport } from './routes/api/public/push.latest'
import { Route as ApiPublicCronDailyDppRouteImport } from './routes/api/public/cron.daily-dpp'
import { Route as ApiPublicCronFinalizeContestsRouteImport } from './routes/api/public/cron.finalize-contests'
import { Route as ApiPublicCronInfiniteRunRouteImport } from './routes/api/public/cron.infinite-run'
import { Route as ApiPublicDiagramIdRouteImport } from './routes/api/public/diagram.$id'
import { Route as ApiPublicHooksDedupeQuestionsRouteImport } from './routes/api/public/hooks/dedupe-questions'
import { Route as ApiPublicHooksGenerateDailyQuizRouteImport } from './routes/api/public/hooks/generate-daily-quiz'
import { Route as ApiPublicHooksGenerateDiagramDppRouteImport } from './routes/api/public/hooks/generate-diagram-dpp'
import { Route as ApiPublicHooksVerifyReportedQuestionsRouteImport } from './routes/api/public/hooks/verify-reported-questions'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay/webhook'
import { Route as ApiPublicTelegramLoginRouteImport } from './routes/api/public/telegram/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollaboratorsRoute = AdminCollaboratorsRouteImport.update({
  id: '/admin-collaborators',
  path: '/admin-collaborators',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPathRoute = AiPathRouteImport.update({
  id: '/ai-path',
  path: '/ai-path',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultRoute = ConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortNotesRoute = ShortNotesRouteImport.update({
  id: '/short-notes',
  path: '/short-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MegaQuizRoute = MegaQuizRouteImport.update({
  id: '/mega-quiz',
  path: '/mega-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const Target700Route = Target700RouteImport.update({
  id: '/target-700',
  path: '/target-700',
  getParentRoute: () => rootRouteImport,
} as any)
const Target700TestTestIdRoute = Target700TestTestIdRouteImport.update({
  id: '/target-700-test/$testId',
  path: '/target-700-test/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesSubjectSlugRoute = NotesSubjectSlugRouteImport.update({
  id: '/notes/$subject/$slug',
  path: '/notes/$subject/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultPlanRoute = ConsultPlanRouteImport.update({
  id: '/consult-plan',
  path: '/consult-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultReportRoute = ConsultReportRouteImport.update({
  id: '/consult-report',
  path: '/consult-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultScoreRoute = ConsultScoreRouteImport.update({
  id: '/consult-score',
  path: '/consult-score',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlegroundsRoute = BattlegroundsRouteImport.update({
  id: '/battlegrounds',
  path: '/battlegrounds',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusRoute = BonusRouteImport.update({
  id: '/bonus',
  path: '/bonus',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaboratorsRoute = CollaboratorsRouteImport.update({
  id: '/collaborators',
  path: '/collaborators',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestsRoute = ContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DedicatedProgramRoute = DedicatedProgramRouteImport.update({
  id: '/dedicated-program',
  path: '/dedicated-program',
  getParentRoute: () => rootRouteImport,
} as any)
const DppRoute = DppRouteImport.update({
  id: '/dpp',
  path: '/dpp',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlightedNcertRoute = HighlightedNcertRouteImport.update({
  id: '/highlighted-ncert',
  path: '/highlighted-ncert',
  getParentRoute: () => rootRouteImport,
} as any)
const InfiniteRunRoute = InfiniteRunRouteImport.update({
  id: '/infinite-run',
  path: '/infinite-run',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipRoute = MentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const MocksRoute = MocksRouteImport.update({
  id: '/mocks',
  path: '/mocks',
  getParentRoute: () => rootRouteImport,
} as any)
const NcertHighlightsRoute = NcertHighlightsRouteImport.update({
  id: '/ncert-highlights',
  path: '/ncert-highlights',
  getParentRoute: () => rootRouteImport,
} as any)
const NeetlabRoute = NeetlabRouteImport.update({
  id: '/neetlab',
  path: '/neetlab',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PyqsRoute = PyqsRouteImport.update({
  id: '/pyqs',
  path: '/pyqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorePredictorRoute = ScorePredictorRouteImport.update({
  id: '/score-predictor',
  path: '/score-predictor',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoRoute = TodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AnalysisAttemptIdRoute = AnalysisAttemptIdRouteImport.update({
  id: '/analysis/$attemptId',
  path: '/analysis/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlegroundsHistoryRoute = BattlegroundsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => BattlegroundsRoute,
} as any)
const BattlegroundsViewAllRoute = BattlegroundsViewAllRouteImport.update({
  id: '/view-all',
  path: '/view-all',
  getParentRoute: () => BattlegroundsRoute,
} as any)
const ContestContestIdRoute = ContestContestIdRouteImport.update({
  id: '/contest/$contestId',
  path: '/contest/$contestId',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewHumanReproductionRoute =
  PreviewHumanReproductionRouteImport.update({
    id: '/preview/human-reproduction',
    path: '/preview/human-reproduction',
    getParentRoute: () => rootRouteImport,
  } as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizTestIdRoute = QuizTestIdRouteImport.update({
  id: '/quiz/$testId',
  path: '/quiz/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectRoute = SubjectsSubjectRouteImport.update({
  id: '/subjects/$subject',
  path: '/subjects/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppVersionRoute = ApiPublicAppVersionRouteImport.update({
  id: '/api/public/app-version',
  path: '/api/public/app-version',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleMatchIdPlayRoute = BattleMatchIdPlayRouteImport.update({
  id: '/battle/$matchId/play',
  path: '/battle/$matchId/play',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleMatchIdResultRoute = BattleMatchIdResultRouteImport.update({
  id: '/battle/$matchId/result',
  path: '/battle/$matchId/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestContestIdJoinRoute = ContestContestIdJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => ContestContestIdRoute,
} as any)
const ContestContestIdResultsRoute = ContestContestIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => ContestContestIdRoute,
} as any)
const ApiPublicCronDailyContestRoute =
  ApiPublicCronDailyContestRouteImport.update({
    id: '/api/public/cron/daily-contest',
    path: '/api/public/cron/daily-contest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronPushRunRoute = ApiPublicCronPushRunRouteImport.update({
  id: '/api/public/cron/push-run',
  path: '/api/public/cron/push-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushLatestRoute = ApiPublicPushLatestRouteImport.update({
  id: '/api/public/push/latest',
  path: '/api/public/push/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDailyDppRoute = ApiPublicCronDailyDppRouteImport.update({
  id: '/api/public/cron/daily-dpp',
  path: '/api/public/cron/daily-dpp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronFinalizeContestsRoute =
  ApiPublicCronFinalizeContestsRouteImport.update({
    id: '/api/public/cron/finalize-contests',
    path: '/api/public/cron/finalize-contests',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronInfiniteRunRoute =
  ApiPublicCronInfiniteRunRouteImport.update({
    id: '/api/public/cron/infinite-run',
    path: '/api/public/cron/infinite-run',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiagramIdRoute = ApiPublicDiagramIdRouteImport.update({
  id: '/api/public/diagram/$id',
  path: '/api/public/diagram/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDedupeQuestionsRoute =
  ApiPublicHooksDedupeQuestionsRouteImport.update({
    id: '/api/public/hooks/dedupe-questions',
    path: '/api/public/hooks/dedupe-questions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateDailyQuizRoute =
  ApiPublicHooksGenerateDailyQuizRouteImport.update({
    id: '/api/public/hooks/generate-daily-quiz',
    path: '/api/public/hooks/generate-daily-quiz',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateDiagramDppRoute =
  ApiPublicHooksGenerateDiagramDppRouteImport.update({
    id: '/api/public/hooks/generate-diagram-dpp',
    path: '/api/public/hooks/generate-diagram-dpp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksVerifyReportedQuestionsRoute =
  ApiPublicHooksVerifyReportedQuestionsRouteImport.update({
    id: '/api/public/hooks/verify-reported-questions',
    path: '/api/public/hooks/verify-reported-questions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay/webhook',
    path: '/api/public/razorpay/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramLoginRoute = ApiPublicTelegramLoginRouteImport.update({
  id: '/api/public/telegram/login',
  path: '/api/public/telegram/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-collaborators': typeof AdminCollaboratorsRoute
  '/ai-path': typeof AiPathRoute
  '/consult': typeof ConsultRoute
  '/short-notes': typeof ShortNotesRoute
  '/mega-quiz': typeof MegaQuizRoute
  '/target-700': typeof Target700Route
  '/target-700-test/$testId': typeof Target700TestTestIdRoute
  '/notes/$subject/$slug': typeof NotesSubjectSlugRoute
  '/consult-plan': typeof ConsultPlanRoute
  '/consult-report': typeof ConsultReportRoute
  '/consult-score': typeof ConsultScoreRoute
  '/analytics': typeof AnalyticsRoute
  '/battlegrounds': typeof BattlegroundsRouteWithChildren
  '/bonus': typeof BonusRoute
  '/bookmarks': typeof BookmarksRoute
  '/collaborators': typeof CollaboratorsRoute
  '/community': typeof CommunityRoute
  '/contests': typeof ContestsRoute
  '/daily': typeof DailyRoute
  '/dashboard': typeof DashboardRoute
  '/dedicated-program': typeof DedicatedProgramRoute
  '/dpp': typeof DppRoute
  '/feedback': typeof FeedbackRoute
  '/flashcards': typeof FlashcardsRoute
  '/generate': typeof GenerateRoute
  '/highlighted-ncert': typeof HighlightedNcertRoute
  '/infinite-run': typeof InfiniteRunRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mentorship': typeof MentorshipRoute
  '/mistakes': typeof MistakesRoute
  '/mocks': typeof MocksRoute
  '/ncert-highlights': typeof NcertHighlightsRoute
  '/neetlab': typeof NeetlabRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/pyqs': typeof PyqsRoute
  '/referrals': typeof ReferralsRoute
  '/score-predictor': typeof ScorePredictorRoute
  '/subscription': typeof SubscriptionRoute
  '/todo': typeof TodoRoute
  '/wallet': typeof WalletRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/support': typeof AdminSupportRoute
  '/analysis/$attemptId': typeof AnalysisAttemptIdRoute
  '/battlegrounds/history': typeof BattlegroundsHistoryRoute
  '/battlegrounds/view-all': typeof BattlegroundsViewAllRoute
  '/contest/$contestId': typeof ContestContestIdRouteWithChildren
  '/preview/human-reproduction': typeof PreviewHumanReproductionRoute
  '/quiz/$testId': typeof QuizTestIdRoute
  '/subjects/$subject': typeof SubjectsSubjectRoute
  '/quiz/': typeof QuizIndexRoute
  '/api/public/app-version': typeof ApiPublicAppVersionRoute
  '/battle/$matchId/play': typeof BattleMatchIdPlayRoute
  '/battle/$matchId/result': typeof BattleMatchIdResultRoute
  '/contest/$contestId/join': typeof ContestContestIdJoinRoute
  '/contest/$contestId/results': typeof ContestContestIdResultsRoute
  '/api/public/cron/daily-contest': typeof ApiPublicCronDailyContestRoute
  '/api/public/cron/push-run': typeof ApiPublicCronPushRunRoute
  '/api/public/push/latest': typeof ApiPublicPushLatestRoute
  '/api/public/cron/daily-dpp': typeof ApiPublicCronDailyDppRoute
  '/api/public/cron/finalize-contests': typeof ApiPublicCronFinalizeContestsRoute
  '/api/public/cron/infinite-run': typeof ApiPublicCronInfiniteRunRoute
  '/api/public/diagram/$id': typeof ApiPublicDiagramIdRoute
  '/api/public/hooks/dedupe-questions': typeof ApiPublicHooksDedupeQuestionsRoute
  '/api/public/hooks/generate-daily-quiz': typeof ApiPublicHooksGenerateDailyQuizRoute
  '/api/public/hooks/generate-diagram-dpp': typeof ApiPublicHooksGenerateDiagramDppRoute
  '/api/public/hooks/verify-reported-questions': typeof ApiPublicHooksVerifyReportedQuestionsRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/telegram/login': typeof ApiPublicTelegramLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-collaborators': typeof AdminCollaboratorsRoute
  '/ai-path': typeof AiPathRoute
  '/consult': typeof ConsultRoute
  '/short-notes': typeof ShortNotesRoute
  '/mega-quiz': typeof MegaQuizRoute
  '/target-700': typeof Target700Route
  '/target-700-test/$testId': typeof Target700TestTestIdRoute
  '/notes/$subject/$slug': typeof NotesSubjectSlugRoute
  '/consult-plan': typeof ConsultPlanRoute
  '/consult-report': typeof ConsultReportRoute
  '/consult-score': typeof ConsultScoreRoute
  '/analytics': typeof AnalyticsRoute
  '/battlegrounds': typeof BattlegroundsRouteWithChildren
  '/bonus': typeof BonusRoute
  '/bookmarks': typeof BookmarksRoute
  '/collaborators': typeof CollaboratorsRoute
  '/community': typeof CommunityRoute
  '/contests': typeof ContestsRoute
  '/daily': typeof DailyRoute
  '/dashboard': typeof DashboardRoute
  '/dedicated-program': typeof DedicatedProgramRoute
  '/dpp': typeof DppRoute
  '/feedback': typeof FeedbackRoute
  '/flashcards': typeof FlashcardsRoute
  '/generate': typeof GenerateRoute
  '/highlighted-ncert': typeof HighlightedNcertRoute
  '/infinite-run': typeof InfiniteRunRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mentorship': typeof MentorshipRoute
  '/mistakes': typeof MistakesRoute
  '/mocks': typeof MocksRoute
  '/ncert-highlights': typeof NcertHighlightsRoute
  '/neetlab': typeof NeetlabRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/pyqs': typeof PyqsRoute
  '/referrals': typeof ReferralsRoute
  '/score-predictor': typeof ScorePredictorRoute
  '/subscription': typeof SubscriptionRoute
  '/todo': typeof TodoRoute
  '/wallet': typeof WalletRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/support': typeof AdminSupportRoute
  '/analysis/$attemptId': typeof AnalysisAttemptIdRoute
  '/battlegrounds/history': typeof BattlegroundsHistoryRoute
  '/battlegrounds/view-all': typeof BattlegroundsViewAllRoute
  '/contest/$contestId': typeof ContestContestIdRouteWithChildren
  '/preview/human-reproduction': typeof PreviewHumanReproductionRoute
  '/quiz/$testId': typeof QuizTestIdRoute
  '/subjects/$subject': typeof SubjectsSubjectRoute
  '/quiz': typeof QuizIndexRoute
  '/api/public/app-version': typeof ApiPublicAppVersionRoute
  '/battle/$matchId/play': typeof BattleMatchIdPlayRoute
  '/battle/$matchId/result': typeof BattleMatchIdResultRoute
  '/contest/$contestId/join': typeof ContestContestIdJoinRoute
  '/contest/$contestId/results': typeof ContestContestIdResultsRoute
  '/api/public/cron/daily-contest': typeof ApiPublicCronDailyContestRoute
  '/api/public/cron/push-run': typeof ApiPublicCronPushRunRoute
  '/api/public/push/latest': typeof ApiPublicPushLatestRoute
  '/api/public/cron/daily-dpp': typeof ApiPublicCronDailyDppRoute
  '/api/public/cron/finalize-contests': typeof ApiPublicCronFinalizeContestsRoute
  '/api/public/cron/infinite-run': typeof ApiPublicCronInfiniteRunRoute
  '/api/public/diagram/$id': typeof ApiPublicDiagramIdRoute
  '/api/public/hooks/dedupe-questions': typeof ApiPublicHooksDedupeQuestionsRoute
  '/api/public/hooks/generate-daily-quiz': typeof ApiPublicHooksGenerateDailyQuizRoute
  '/api/public/hooks/generate-diagram-dpp': typeof ApiPublicHooksGenerateDiagramDppRoute
  '/api/public/hooks/verify-reported-questions': typeof ApiPublicHooksVerifyReportedQuestionsRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/telegram/login': typeof ApiPublicTelegramLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-collaborators': typeof AdminCollaboratorsRoute
  '/ai-path': typeof AiPathRoute
  '/consult': typeof ConsultRoute
  '/short-notes': typeof ShortNotesRoute
  '/mega-quiz': typeof MegaQuizRoute
  '/target-700': typeof Target700Route
  '/target-700-test/$testId': typeof Target700TestTestIdRoute
  '/notes/$subject/$slug': typeof NotesSubjectSlugRoute
  '/consult-plan': typeof ConsultPlanRoute
  '/consult-report': typeof ConsultReportRoute
  '/consult-score': typeof ConsultScoreRoute
  '/analytics': typeof AnalyticsRoute
  '/battlegrounds': typeof BattlegroundsRouteWithChildren
  '/bonus': typeof BonusRoute
  '/bookmarks': typeof BookmarksRoute
  '/collaborators': typeof CollaboratorsRoute
  '/community': typeof CommunityRoute
  '/contests': typeof ContestsRoute
  '/daily': typeof DailyRoute
  '/dashboard': typeof DashboardRoute
  '/dedicated-program': typeof DedicatedProgramRoute
  '/dpp': typeof DppRoute
  '/feedback': typeof FeedbackRoute
  '/flashcards': typeof FlashcardsRoute
  '/generate': typeof GenerateRoute
  '/highlighted-ncert': typeof HighlightedNcertRoute
  '/infinite-run': typeof InfiniteRunRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mentorship': typeof MentorshipRoute
  '/mistakes': typeof MistakesRoute
  '/mocks': typeof MocksRoute
  '/ncert-highlights': typeof NcertHighlightsRoute
  '/neetlab': typeof NeetlabRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/pyqs': typeof PyqsRoute
  '/referrals': typeof ReferralsRoute
  '/score-predictor': typeof ScorePredictorRoute
  '/subscription': typeof SubscriptionRoute
  '/todo': typeof TodoRoute
  '/wallet': typeof WalletRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/support': typeof AdminSupportRoute
  '/analysis/$attemptId': typeof AnalysisAttemptIdRoute
  '/battlegrounds/history': typeof BattlegroundsHistoryRoute
  '/battlegrounds/view-all': typeof BattlegroundsViewAllRoute
  '/contest/$contestId': typeof ContestContestIdRouteWithChildren
  '/preview/human-reproduction': typeof PreviewHumanReproductionRoute
  '/quiz/$testId': typeof QuizTestIdRoute
  '/subjects/$subject': typeof SubjectsSubjectRoute
  '/quiz/': typeof QuizIndexRoute
  '/api/public/app-version': typeof ApiPublicAppVersionRoute
  '/battle/$matchId/play': typeof BattleMatchIdPlayRoute
  '/battle/$matchId/result': typeof BattleMatchIdResultRoute
  '/contest/$contestId/join': typeof ContestContestIdJoinRoute
  '/contest/$contestId/results': typeof ContestContestIdResultsRoute
  '/api/public/cron/daily-contest': typeof ApiPublicCronDailyContestRoute
  '/api/public/cron/push-run': typeof ApiPublicCronPushRunRoute
  '/api/public/push/latest': typeof ApiPublicPushLatestRoute
  '/api/public/cron/daily-dpp': typeof ApiPublicCronDailyDppRoute
  '/api/public/cron/finalize-contests': typeof ApiPublicCronFinalizeContestsRoute
  '/api/public/cron/infinite-run': typeof ApiPublicCronInfiniteRunRoute
  '/api/public/diagram/$id': typeof ApiPublicDiagramIdRoute
  '/api/public/hooks/dedupe-questions': typeof ApiPublicHooksDedupeQuestionsRoute
  '/api/public/hooks/generate-daily-quiz': typeof ApiPublicHooksGenerateDailyQuizRoute
  '/api/public/hooks/generate-diagram-dpp': typeof ApiPublicHooksGenerateDiagramDppRoute
  '/api/public/hooks/verify-reported-questions': typeof ApiPublicHooksVerifyReportedQuestionsRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/telegram/login': typeof ApiPublicTelegramLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-collaborators'
    | '/ai-path'
    | '/consult'
    | '/short-notes'
    | '/mega-quiz'
    | '/target-700'
    | '/target-700-test/$testId'
    | '/notes/$subject/$slug'
    | '/consult-plan'
    | '/consult-report'
    | '/consult-score'
    | '/analytics'
    | '/battlegrounds'
    | '/bonus'
    | '/bookmarks'
    | '/collaborators'
    | '/community'
    | '/contests'
    | '/daily'
    | '/dashboard'
    | '/dedicated-program'
    | '/dpp'
    | '/feedback'
    | '/flashcards'
    | '/generate'
    | '/highlighted-ncert'
    | '/infinite-run'
    | '/leaderboard'
    | '/login'
    | '/mentorship'
    | '/mistakes'
    | '/mocks'
    | '/ncert-highlights'
    | '/neetlab'
    | '/premium'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/pyqs'
    | '/referrals'
    | '/score-predictor'
    | '/subscription'
    | '/todo'
    | '/wallet'
    | '/admin/feedback'
    | '/admin/inbox'
    | '/admin/support'
    | '/analysis/$attemptId'
    | '/battlegrounds/history'
    | '/battlegrounds/view-all'
    | '/contest/$contestId'
    | '/preview/human-reproduction'
    | '/quiz/$testId'
    | '/subjects/$subject'
    | '/quiz/'
    | '/api/public/app-version'
    | '/battle/$matchId/play'
    | '/battle/$matchId/result'
    | '/contest/$contestId/join'
    | '/contest/$contestId/results'
    | '/api/public/cron/daily-contest'
    | '/api/public/cron/push-run'
    | '/api/public/push/latest'
    | '/api/public/cron/daily-dpp'
    | '/api/public/cron/finalize-contests'
    | '/api/public/cron/infinite-run'
    | '/api/public/diagram/$id'
    | '/api/public/hooks/dedupe-questions'
    | '/api/public/hooks/generate-daily-quiz'
    | '/api/public/hooks/generate-diagram-dpp'
    | '/api/public/hooks/verify-reported-questions'
    | '/api/public/razorpay/webhook'
    | '/api/public/telegram/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-collaborators'
    | '/ai-path'
    | '/consult'
    | '/short-notes'
    | '/mega-quiz'
    | '/target-700'
    | '/target-700-test/$testId'
    | '/notes/$subject/$slug'
    | '/consult-plan'
    | '/consult-report'
    | '/consult-score'
    | '/analytics'
    | '/battlegrounds'
    | '/bonus'
    | '/bookmarks'
    | '/collaborators'
    | '/community'
    | '/contests'
    | '/daily'
    | '/dashboard'
    | '/dedicated-program'
    | '/dpp'
    | '/feedback'
    | '/flashcards'
    | '/generate'
    | '/highlighted-ncert'
    | '/infinite-run'
    | '/leaderboard'
    | '/login'
    | '/mentorship'
    | '/mistakes'
    | '/mocks'
    | '/ncert-highlights'
    | '/neetlab'
    | '/premium'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/pyqs'
    | '/referrals'
    | '/score-predictor'
    | '/subscription'
    | '/todo'
    | '/wallet'
    | '/admin/feedback'
    | '/admin/inbox'
    | '/admin/support'
    | '/analysis/$attemptId'
    | '/battlegrounds/history'
    | '/battlegrounds/view-all'
    | '/contest/$contestId'
    | '/preview/human-reproduction'
    | '/quiz/$testId'
    | '/subjects/$subject'
    | '/quiz'
    | '/api/public/app-version'
    | '/battle/$matchId/play'
    | '/battle/$matchId/result'
    | '/contest/$contestId/join'
    | '/contest/$contestId/results'
    | '/api/public/cron/daily-contest'
    | '/api/public/cron/push-run'
    | '/api/public/push/latest'
    | '/api/public/cron/daily-dpp'
    | '/api/public/cron/finalize-contests'
    | '/api/public/cron/infinite-run'
    | '/api/public/diagram/$id'
    | '/api/public/hooks/dedupe-questions'
    | '/api/public/hooks/generate-daily-quiz'
    | '/api/public/hooks/generate-diagram-dpp'
    | '/api/public/hooks/verify-reported-questions'
    | '/api/public/razorpay/webhook'
    | '/api/public/telegram/login'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-collaborators'
    | '/ai-path'
    | '/consult'
    | '/short-notes'
    | '/mega-quiz'
    | '/target-700'
    | '/target-700-test/$testId'
    | '/notes/$subject/$slug'
    | '/consult-plan'
    | '/consult-report'
    | '/consult-score'
    | '/analytics'
    | '/battlegrounds'
    | '/bonus'
    | '/bookmarks'
    | '/collaborators'
    | '/community'
    | '/contests'
    | '/daily'
    | '/dashboard'
    | '/dedicated-program'
    | '/dpp'
    | '/feedback'
    | '/flashcards'
    | '/generate'
    | '/highlighted-ncert'
    | '/infinite-run'
    | '/leaderboard'
    | '/login'
    | '/mentorship'
    | '/mistakes'
    | '/mocks'
    | '/ncert-highlights'
    | '/neetlab'
    | '/premium'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/pyqs'
    | '/referrals'
    | '/score-predictor'
    | '/subscription'
    | '/todo'
    | '/wallet'
    | '/admin/feedback'
    | '/admin/inbox'
    | '/admin/support'
    | '/analysis/$attemptId'
    | '/battlegrounds/history'
    | '/battlegrounds/view-all'
    | '/contest/$contestId'
    | '/preview/human-reproduction'
    | '/quiz/$testId'
    | '/subjects/$subject'
    | '/quiz/'
    | '/api/public/app-version'
    | '/battle/$matchId/play'
    | '/battle/$matchId/result'
    | '/contest/$contestId/join'
    | '/contest/$contestId/results'
    | '/api/public/cron/daily-contest'
    | '/api/public/cron/push-run'
    | '/api/public/push/latest'
    | '/api/public/cron/daily-dpp'
    | '/api/public/cron/finalize-contests'
    | '/api/public/cron/infinite-run'
    | '/api/public/diagram/$id'
    | '/api/public/hooks/dedupe-questions'
    | '/api/public/hooks/generate-daily-quiz'
    | '/api/public/hooks/generate-diagram-dpp'
    | '/api/public/hooks/verify-reported-questions'
    | '/api/public/razorpay/webhook'
    | '/api/public/telegram/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminCollaboratorsRoute: typeof AdminCollaboratorsRoute
  AiPathRoute: typeof AiPathRoute
  ConsultRoute: typeof ConsultRoute
  ShortNotesRoute: typeof ShortNotesRoute
  MegaQuizRoute: typeof MegaQuizRoute
  Target700Route: typeof Target700Route
  Target700TestTestIdRoute: typeof Target700TestTestIdRoute
  NotesSubjectSlugRoute: typeof NotesSubjectSlugRoute
  ConsultPlanRoute: typeof ConsultPlanRoute
  ConsultReportRoute: typeof ConsultReportRoute
  ConsultScoreRoute: typeof ConsultScoreRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BattlegroundsRoute: typeof BattlegroundsRouteWithChildren
  BonusRoute: typeof BonusRoute
  BookmarksRoute: typeof BookmarksRoute
  CollaboratorsRoute: typeof CollaboratorsRoute
  CommunityRoute: typeof CommunityRoute
  ContestsRoute: typeof ContestsRoute
  DailyRoute: typeof DailyRoute
  DashboardRoute: typeof DashboardRoute
  DedicatedProgramRoute: typeof DedicatedProgramRoute
  DppRoute: typeof DppRoute
  FeedbackRoute: typeof FeedbackRoute
  FlashcardsRoute: typeof FlashcardsRoute
  GenerateRoute: typeof GenerateRoute
  HighlightedNcertRoute: typeof HighlightedNcertRoute
  InfiniteRunRoute: typeof InfiniteRunRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MentorshipRoute: typeof MentorshipRoute
  MistakesRoute: typeof MistakesRoute
  MocksRoute: typeof MocksRoute
  NcertHighlightsRoute: typeof NcertHighlightsRoute
  NeetlabRoute: typeof NeetlabRoute
  PremiumRoute: typeof PremiumRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  PyqsRoute: typeof PyqsRoute
  ReferralsRoute: typeof ReferralsRoute
  ScorePredictorRoute: typeof ScorePredictorRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TodoRoute: typeof TodoRoute
  WalletRoute: typeof WalletRoute
  AnalysisAttemptIdRoute: typeof AnalysisAttemptIdRoute
  ContestContestIdRoute: typeof ContestContestIdRouteWithChildren
  PreviewHumanReproductionRoute: typeof PreviewHumanReproductionRoute
  QuizTestIdRoute: typeof QuizTestIdRoute
  SubjectsSubjectRoute: typeof SubjectsSubjectRoute
  QuizIndexRoute: typeof QuizIndexRoute
  ApiPublicAppVersionRoute: typeof ApiPublicAppVersionRoute
  BattleMatchIdPlayRoute: typeof BattleMatchIdPlayRoute
  BattleMatchIdResultRoute: typeof BattleMatchIdResultRoute
  ApiPublicCronDailyContestRoute: typeof ApiPublicCronDailyContestRoute
  ApiPublicCronPushRunRoute: typeof ApiPublicCronPushRunRoute
  ApiPublicPushLatestRoute: typeof ApiPublicPushLatestRoute
  ApiPublicCronDailyDppRoute: typeof ApiPublicCronDailyDppRoute
  ApiPublicCronFinalizeContestsRoute: typeof ApiPublicCronFinalizeContestsRoute
  ApiPublicCronInfiniteRunRoute: typeof ApiPublicCronInfiniteRunRoute
  ApiPublicDiagramIdRoute: typeof ApiPublicDiagramIdRoute
  ApiPublicHooksDedupeQuestionsRoute: typeof ApiPublicHooksDedupeQuestionsRoute
  ApiPublicHooksGenerateDailyQuizRoute: typeof ApiPublicHooksGenerateDailyQuizRoute
  ApiPublicHooksGenerateDiagramDppRoute: typeof ApiPublicHooksGenerateDiagramDppRoute
  ApiPublicHooksVerifyReportedQuestionsRoute: typeof ApiPublicHooksVerifyReportedQuestionsRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiPublicTelegramLoginRoute: typeof ApiPublicTelegramLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-collaborators': {
      id: '/admin-collaborators'
      path: '/admin-collaborators'
      fullPath: '/admin-collaborators'
      preLoaderRoute: typeof AdminCollaboratorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-path': {
      id: '/ai-path'
      path: '/ai-path'
      fullPath: '/ai-path'
      preLoaderRoute: typeof AiPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult': {
      id: '/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof ConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/short-notes': {
      id: '/short-notes'
      path: '/short-notes'
      fullPath: '/short-notes'
      preLoaderRoute: typeof ShortNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mega-quiz': {
      id: '/mega-quiz'
      path: '/mega-quiz'
      fullPath: '/mega-quiz'
      preLoaderRoute: typeof MegaQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/target-700': {
      id: '/target-700'
      path: '/target-700'
      fullPath: '/target-700'
      preLoaderRoute: typeof Target700RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/target-700-test/$testId': {
      id: '/target-700-test/$testId'
      path: '/target-700-test/$testId'
      fullPath: '/target-700-test/$testId'
      preLoaderRoute: typeof Target700TestTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$subject/$slug': {
      id: '/notes/$subject/$slug'
      path: '/notes/$subject/$slug'
      fullPath: '/notes/$subject/$slug'
      preLoaderRoute: typeof NotesSubjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult-plan': {
      id: '/consult-plan'
      path: '/consult-plan'
      fullPath: '/consult-plan'
      preLoaderRoute: typeof ConsultPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult-report': {
      id: '/consult-report'
      path: '/consult-report'
      fullPath: '/consult-report'
      preLoaderRoute: typeof ConsultReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult-score': {
      id: '/consult-score'
      path: '/consult-score'
      fullPath: '/consult-score'
      preLoaderRoute: typeof ConsultScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battlegrounds': {
      id: '/battlegrounds'
      path: '/battlegrounds'
      fullPath: '/battlegrounds'
      preLoaderRoute: typeof BattlegroundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonus': {
      id: '/bonus'
      path: '/bonus'
      fullPath: '/bonus'
      preLoaderRoute: typeof BonusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborators': {
      id: '/collaborators'
      path: '/collaborators'
      fullPath: '/collaborators'
      preLoaderRoute: typeof CollaboratorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests': {
      id: '/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof ContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dedicated-program': {
      id: '/dedicated-program'
      path: '/dedicated-program'
      fullPath: '/dedicated-program'
      preLoaderRoute: typeof DedicatedProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpp': {
      id: '/dpp'
      path: '/dpp'
      fullPath: '/dpp'
      preLoaderRoute: typeof DppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlighted-ncert': {
      id: '/highlighted-ncert'
      path: '/highlighted-ncert'
      fullPath: '/highlighted-ncert'
      preLoaderRoute: typeof HighlightedNcertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infinite-run': {
      id: '/infinite-run'
      path: '/infinite-run'
      fullPath: '/infinite-run'
      preLoaderRoute: typeof InfiniteRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship': {
      id: '/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof MentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mocks': {
      id: '/mocks'
      path: '/mocks'
      fullPath: '/mocks'
      preLoaderRoute: typeof MocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ncert-highlights': {
      id: '/ncert-highlights'
      path: '/ncert-highlights'
      fullPath: '/ncert-highlights'
      preLoaderRoute: typeof NcertHighlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neetlab': {
      id: '/neetlab'
      path: '/neetlab'
      fullPath: '/neetlab'
      preLoaderRoute: typeof NeetlabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pyqs': {
      id: '/pyqs'
      path: '/pyqs'
      fullPath: '/pyqs'
      preLoaderRoute: typeof PyqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score-predictor': {
      id: '/score-predictor'
      path: '/score-predictor'
      fullPath: '/score-predictor'
      preLoaderRoute: typeof ScorePredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/analysis/$attemptId': {
      id: '/analysis/$attemptId'
      path: '/analysis/$attemptId'
      fullPath: '/analysis/$attemptId'
      preLoaderRoute: typeof AnalysisAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battlegrounds/history': {
      id: '/battlegrounds/history'
      path: '/history'
      fullPath: '/battlegrounds/history'
      preLoaderRoute: typeof BattlegroundsHistoryRouteImport
      parentRoute: typeof BattlegroundsRoute
    }
    '/battlegrounds/view-all': {
      id: '/battlegrounds/view-all'
      path: '/view-all'
      fullPath: '/battlegrounds/view-all'
      preLoaderRoute: typeof BattlegroundsViewAllRouteImport
      parentRoute: typeof BattlegroundsRoute
    }
    '/contest/$contestId': {
      id: '/contest/$contestId'
      path: '/contest/$contestId'
      fullPath: '/contest/$contestId'
      preLoaderRoute: typeof ContestContestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/human-reproduction': {
      id: '/preview/human-reproduction'
      path: '/preview/human-reproduction'
      fullPath: '/preview/human-reproduction'
      preLoaderRoute: typeof PreviewHumanReproductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$testId': {
      id: '/quiz/$testId'
      path: '/quiz/$testId'
      fullPath: '/quiz/$testId'
      preLoaderRoute: typeof QuizTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subject': {
      id: '/subjects/$subject'
      path: '/subjects/$subject'
      fullPath: '/subjects/$subject'
      preLoaderRoute: typeof SubjectsSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/app-version': {
      id: '/api/public/app-version'
      path: '/api/public/app-version'
      fullPath: '/api/public/app-version'
      preLoaderRoute: typeof ApiPublicAppVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle/$matchId/play': {
      id: '/battle/$matchId/play'
      path: '/battle/$matchId/play'
      fullPath: '/battle/$matchId/play'
      preLoaderRoute: typeof BattleMatchIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle/$matchId/result': {
      id: '/battle/$matchId/result'
      path: '/battle/$matchId/result'
      fullPath: '/battle/$matchId/result'
      preLoaderRoute: typeof BattleMatchIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest/$contestId/join': {
      id: '/contest/$contestId/join'
      path: '/join'
      fullPath: '/contest/$contestId/join'
      preLoaderRoute: typeof ContestContestIdJoinRouteImport
      parentRoute: typeof ContestContestIdRoute
    }
    '/contest/$contestId/results': {
      id: '/contest/$contestId/results'
      path: '/results'
      fullPath: '/contest/$contestId/results'
      preLoaderRoute: typeof ContestContestIdResultsRouteImport
      parentRoute: typeof ContestContestIdRoute
    }
    '/api/public/cron/daily-contest': {
      id: '/api/public/cron/daily-contest'
      path: '/api/public/cron/daily-contest'
      fullPath: '/api/public/cron/daily-contest'
      preLoaderRoute: typeof ApiPublicCronDailyContestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/push-run': {
      id: '/api/public/cron/push-run'
      path: '/api/public/cron/push-run'
      fullPath: '/api/public/cron/push-run'
      preLoaderRoute: typeof ApiPublicCronPushRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/latest': {
      id: '/api/public/push/latest'
      path: '/api/public/push/latest'
      fullPath: '/api/public/push/latest'
      preLoaderRoute: typeof ApiPublicPushLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily-dpp': {
      id: '/api/public/cron/daily-dpp'
      path: '/api/public/cron/daily-dpp'
      fullPath: '/api/public/cron/daily-dpp'
      preLoaderRoute: typeof ApiPublicCronDailyDppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/finalize-contests': {
      id: '/api/public/cron/finalize-contests'
      path: '/api/public/cron/finalize-contests'
      fullPath: '/api/public/cron/finalize-contests'
      preLoaderRoute: typeof ApiPublicCronFinalizeContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/infinite-run': {
      id: '/api/public/cron/infinite-run'
      path: '/api/public/cron/infinite-run'
      fullPath: '/api/public/cron/infinite-run'
      preLoaderRoute: typeof ApiPublicCronInfiniteRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diagram/$id': {
      id: '/api/public/diagram/$id'
      path: '/api/public/diagram/$id'
      fullPath: '/api/public/diagram/$id'
      preLoaderRoute: typeof ApiPublicDiagramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dedupe-questions': {
      id: '/api/public/hooks/dedupe-questions'
      path: '/api/public/hooks/dedupe-questions'
      fullPath: '/api/public/hooks/dedupe-questions'
      preLoaderRoute: typeof ApiPublicHooksDedupeQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-daily-quiz': {
      id: '/api/public/hooks/generate-daily-quiz'
      path: '/api/public/hooks/generate-daily-quiz'
      fullPath: '/api/public/hooks/generate-daily-quiz'
      preLoaderRoute: typeof ApiPublicHooksGenerateDailyQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-diagram-dpp': {
      id: '/api/public/hooks/generate-diagram-dpp'
      path: '/api/public/hooks/generate-diagram-dpp'
      fullPath: '/api/public/hooks/generate-diagram-dpp'
      preLoaderRoute: typeof ApiPublicHooksGenerateDiagramDppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/verify-reported-questions': {
      id: '/api/public/hooks/verify-reported-questions'
      path: '/api/public/hooks/verify-reported-questions'
      fullPath: '/api/public/hooks/verify-reported-questions'
      preLoaderRoute: typeof ApiPublicHooksVerifyReportedQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay/webhook': {
      id: '/api/public/razorpay/webhook'
      path: '/api/public/razorpay/webhook'
      fullPath: '/api/public/razorpay/webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/login': {
      id: '/api/public/telegram/login'
      path: '/api/public/telegram/login'
      fullPath: '/api/public/telegram/login'
      preLoaderRoute: typeof ApiPublicTelegramLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminSupportRoute: typeof AdminSupportRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminSupportRoute: AdminSupportRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BattlegroundsRouteChildren {
  BattlegroundsHistoryRoute: typeof BattlegroundsHistoryRoute
  BattlegroundsViewAllRoute: typeof BattlegroundsViewAllRoute
}

const BattlegroundsRouteChildren: BattlegroundsRouteChildren = {
  BattlegroundsHistoryRoute: BattlegroundsHistoryRoute,
  BattlegroundsViewAllRoute: BattlegroundsViewAllRoute,
}

const BattlegroundsRouteWithChildren = BattlegroundsRoute._addFileChildren(
  BattlegroundsRouteChildren,
)

interface ContestContestIdRouteChildren {
  ContestContestIdJoinRoute: typeof ContestContestIdJoinRoute
  ContestContestIdResultsRoute: typeof ContestContestIdResultsRoute
}

const ContestContestIdRouteChildren: ContestContestIdRouteChildren = {
  ContestContestIdJoinRoute: ContestContestIdJoinRoute,
  ContestContestIdResultsRoute: ContestContestIdResultsRoute,
}

const ContestContestIdRouteWithChildren =
  ContestContestIdRoute._addFileChildren(ContestContestIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminCollaboratorsRoute: AdminCollaboratorsRoute,
  AiPathRoute: AiPathRoute,
  ConsultRoute: ConsultRoute,
  ShortNotesRoute: ShortNotesRoute,
  MegaQuizRoute: MegaQuizRoute,
  Target700Route: Target700Route,
  Target700TestTestIdRoute: Target700TestTestIdRoute,
  NotesSubjectSlugRoute: NotesSubjectSlugRoute,
  ConsultPlanRoute: ConsultPlanRoute,
  ConsultReportRoute: ConsultReportRoute,
  ConsultScoreRoute: ConsultScoreRoute,
  AnalyticsRoute: AnalyticsRoute,
  BattlegroundsRoute: BattlegroundsRouteWithChildren,
  BonusRoute: BonusRoute,
  BookmarksRoute: BookmarksRoute,
  CollaboratorsRoute: CollaboratorsRoute,
  CommunityRoute: CommunityRoute,
  ContestsRoute: ContestsRoute,
  DailyRoute: DailyRoute,
  DashboardRoute: DashboardRoute,
  DedicatedProgramRoute: DedicatedProgramRoute,
  DppRoute: DppRoute,
  FeedbackRoute: FeedbackRoute,
  FlashcardsRoute: FlashcardsRoute,
  GenerateRoute: GenerateRoute,
  HighlightedNcertRoute: HighlightedNcertRoute,
  InfiniteRunRoute: InfiniteRunRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MentorshipRoute: MentorshipRoute,
  MistakesRoute: MistakesRoute,
  MocksRoute: MocksRoute,
  NcertHighlightsRoute: NcertHighlightsRoute,
  NeetlabRoute: NeetlabRoute,
  PremiumRoute: PremiumRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  PyqsRoute: PyqsRoute,
  ReferralsRoute: ReferralsRoute,
  ScorePredictorRoute: ScorePredictorRoute,
  SubscriptionRoute: SubscriptionRoute,
  TodoRoute: TodoRoute,
  WalletRoute: WalletRoute,
  AnalysisAttemptIdRoute: AnalysisAttemptIdRoute,
  ContestContestIdRoute: ContestContestIdRouteWithChildren,
  PreviewHumanReproductionRoute: PreviewHumanReproductionRoute,
  QuizTestIdRoute: QuizTestIdRoute,
  SubjectsSubjectRoute: SubjectsSubjectRoute,
  QuizIndexRoute: QuizIndexRoute,
  ApiPublicAppVersionRoute: ApiPublicAppVersionRoute,
  BattleMatchIdPlayRoute: BattleMatchIdPlayRoute,
  BattleMatchIdResultRoute: BattleMatchIdResultRoute,
  ApiPublicCronDailyContestRoute: ApiPublicCronDailyContestRoute,
  ApiPublicCronPushRunRoute: ApiPublicCronPushRunRoute,
  ApiPublicPushLatestRoute: ApiPublicPushLatestRoute,
  ApiPublicCronDailyDppRoute: ApiPublicCronDailyDppRoute,
  ApiPublicCronFinalizeContestsRoute: ApiPublicCronFinalizeContestsRoute,
  ApiPublicCronInfiniteRunRoute: ApiPublicCronInfiniteRunRoute,
  ApiPublicDiagramIdRoute: ApiPublicDiagramIdRoute,
  ApiPublicHooksDedupeQuestionsRoute: ApiPublicHooksDedupeQuestionsRoute,
  ApiPublicHooksGenerateDailyQuizRoute: ApiPublicHooksGenerateDailyQuizRoute,
  ApiPublicHooksGenerateDiagramDppRoute: ApiPublicHooksGenerateDiagramDppRoute,
  ApiPublicHooksVerifyReportedQuestionsRoute:
    ApiPublicHooksVerifyReportedQuestionsRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiPublicTelegramLoginRoute: ApiPublicTelegramLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
